### ISSUE TITLE
Exception when running python 3 on windows 7

### ISSUE THREAD

**Issue by Vitruvia** [LightTable/Python#54]
I just installed LightTable and used it fine with JavaScript, but when I tried using python 3 I got this exception:

> Traceback (most recent call last):
>   File "P:\LightTable\resources\app\plugins\Python\py-src\ltmain.py", line 193, in handleEval
>     code= compile(ensureUtf(code), ensureUtf(data[2]["name"]), 'eval')
>   File "P:\LightTable\resources\app\plugins\Python\py-src\ltmain.py", line 50, in ensureUtf
>     if type(s) == unicode:
> NameError: name 'unicode' is not defined
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "P:\LightTable\resources\app\plugins\Python\py-src\ltmain.py", line 197, in handleEval
>     code= compile(ensureUtf(code), ensureUtf(data[2]["name"]), 'exec')
>   File "P:\LightTable\resources\app\plugins\Python\py-src\ltmain.py", line 50, in ensureUtf
>     if type(s) == unicode:
> NameError: name 'unicode' is not defined

What I did was assign `a = 3` just to see if there were no problems, and I got this after running with ctr+shift+enter.

**Comment by sbauer322** [comment]
@Vitruvia could pull down the work from PR https://github.com/LightTable/Python/pull/47 and give it a try? It might address the problem.

Unfortunately, the Python plugin is in need of a maintainer and has a backlog of PRs and issues to address. The position is open to pretty much anyone who is willing and able to work on it.

**Comment by Vitruvia** [comment]
@sbauer322 Thanks for the help!

Well... I wouldn't mind helping out but I only begun programming a month ago. Is there anything I could do at this level?

**Comment by sbauer322** [comment]
Sure, there are few ways to help out at that stage!

Since you are still learning programming, the biggest help would reporting any bugs you might come across. Attempting to reproduce new issues would be beneficial also, but of lesser importance.

Another helpful thing would be testing out pull requests to make sure they work and do not introduce any new problem.

**Comment by Vitruvia** [comment]
Great, I'll keep reporting anything I find. I'll also check for pull requests later.

By the way, the solution you suggested works, so in case anyone is experiencing this bug just refer to PR #47.

**Comment by sbauer322** [comment]
Thanks for confirming the PR works!
